dist: xenial
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install pipenv
    - pipenv sync
script:
    - find -name *.py | xargs pipenv run pylint --max-line-length=79
