dist: xenial
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install pipenv
    - pipenv sync
script:
    - pipenv shell
    - find -name *.py | xargs pylint --max-line-length=79
    - pydocstyle
